### ISSUE TITLE
Agent number do not recognize 42 in words

### ISSUE THREAD

**Issue by odespesse** [viky-ai/viky-ai#31]
**Agent**

https://www.viky.ai/agents/viky/numbers

**Description**

The agent is not able to understand any number ending by "forty-two"

**How to reproduce it (as minimally and precisely as possible)**

- In the console type the sentence "two hundred and forty-two"
- Default options

**Expected behavior**

number (viky/numbers)
```
 {
   "number": 242
}
```

**Actual behavior** 

The agent returns two interpretations:
- number (viky/numbers)
```
 {
   "number": 200
}
```
- number (viky/numbers)

```
{
 "number": 2
}
```

**Comment by PatrickConstant** [comment]
the name only fourty, I just added also forty. Fix was done in https://www.viky.ai/agents/viky/numbers/interpretations/voc_40
