### ISSUE TITLE
Agent number do not recognize 12th in words

### ISSUE THREAD

**Issue by odespesse** [viky-ai/viky-ai#32]
**Agent**

https://www.viky.ai/agents/viky/numbers

**Description**

The agent is not able to understand the expression "twelfth".

**How to reproduce it (as minimally and precisely as possible)**

- In the console submit the sentence "twelfth"
- Default options

**Expected behavior**

 number_ordinal (viky/numbers)
```
{
  "number": 12
}
```

**Actual behavior** 

No interpretation found.

**Additional context**

It works with the french translation "douzième".

**Comment by PatrickConstant** [comment]
Interpretation corrected from twelvth to twelfth. Interpretation is: https://www.viky.ai/agents/viky/numbers/interpretations/voc_12_ordinal
