### ISSUE TITLE
Agent date ignore the year after a comma

### ISSUE THREAD

**Issue by odespesse** [viky-ai/viky-ai#37]
**Agent**

https://www.viky.ai/agents/viky/date

**Description**

The agent does not detect the year when the date is followed by a comma separated year like "September 6, 2019"

**How to reproduce it (as minimally and precisely as possible)**

- In the console submit the sentence "September 6, 2019"
- Default options

**Expected behavior**

date (viky/date)
```
{
  "date": "2019-09-06T00:00:00Z"
}
```

**Actual behavior** 

date (viky/date)
```
{
  "date": "2020-09-06T00:00:00Z"
}
```

**Additional context**

Add any other context about the problem here (ex. request sent on the public API or the console).

**Comment by PatrickConstant** [comment]
The following forms have been added "September 6 2019", "September 6, 2019", "September 6th 2019", "September 6th, 2019".
